//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    
    public partial class SubjectInterTable
    {
        public string IID { get; set; }
        public string Name { get; set; }
        public int Id { get; set; }
        public int SubjectCategoryId { get; set; }
        public bool Status { get; set; }
    }
}
